version: "3.8"

services:
  lab:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lab_web
    ports:
      - "8054:80"

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: lab_bot
    environment:
      BASE_URL: http://lab
      ADMIN_USER: admin
      ADMIN_PASS: eclipse
      FLAG: ECLIPSE{y0u_f0und_1t}
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium
    depends_on:
      - lab
